name: minilist
description: A thoughtful, minimalistic shopping list.
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^3.1.2
  basics: ^0.6.0
  black_hole_flutter: ^0.3.0
  chest_flutter: ^0.1.2
  cupertino_icons: ^1.0.1
  file_picker: ^3.0.1
  google_fonts: ^2.0.0
  meta: ^1.3.0
  path_provider: ^2.0.1
  reorderables: ^0.4.0
  screenshot: ^0.3.0
  share: ^2.0.1
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  tapegen:
    path: ../chestdb/tapegen
  build_runner: any
  flutter_launcher_icons: ^0.9.0
  test: any

dependency_overrides:
  analyzer: ^0.41.1

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  image_path: "icon_round.png"
