name: minilist
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.10.0-0 <3.0.0"

dependencies:
  basics: any
  black_hole_flutter: any
  chest_flutter:
    path: ../chestdb/chest_flutter
  cupertino_icons: ^1.0.1
  flutter:
    sdk: flutter
  flutter_statusbarcolor: any
  google_fonts: any
  meta: any
  reorderables: ^0.3.2
  url_launcher: any

dev_dependencies:
  build_runner: any
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter
  test: any
  screenshots: ^2.1.1
  tapegen:
    path: ../chestdb/tapegen

dependency_overrides:
  analyzer: ^0.41.1

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  image_path: "icon.png"
